spring.application.name=FileUpload
spring.datasource.url=jdbc:mysql://localhost/fileuplaod
spring.datasource.username=root
spring.datasource.password=root123
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create

# PostGreSql
#spring.datasource.postgredb.jdbc-url=jdbc:postgresql://localhost/fileupload
#spring.datasource.postgredb.username=postgres
#spring.datasource.postgredb.password=root123
#spring.jpa.hibernate.postgredb.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true